<template>
<div class="spinner-2">
  <div class="loadingio-spinner-dual-ring-s7tzyhrrfx9"><div class="ldio-t31fo04ebks">
  <div></div><div><div></div></div>
  </div></div>
</div>
</template>

<script>
export default {
    name: "Spinner"
};
</script>

<style lang="scss">
.spinner-2{
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  background: rgba(245, 222, 148, 0.476);
  border-radius: 5rem;
}
@keyframes ldio-t31fo04ebks {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-t31fo04ebks div { box-sizing: border-box!important }
.ldio-t31fo04ebks > div {
  position: absolute;
  width: 72px;
  height: 72px;
  top: 14px;
  left: 14px;
  border-radius: 50%;
  border: 8px solid #000;
  border-color: #05114f transparent #05114f transparent;
  animation: ldio-t31fo04ebks 1s linear infinite;
}
.ldio-t31fo04ebks > div:nth-child(2) { border-color: transparent }
.ldio-t31fo04ebks > div:nth-child(2) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-t31fo04ebks > div:nth-child(2) div:before, .ldio-t31fo04ebks > div:nth-child(2) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 8px;
  height: 8px;
  top: -8px;
  left: 24px;
  background: #05114f;
  border-radius: 50%;
  box-shadow: 0 64px 0 0 #05114f;
}
.ldio-t31fo04ebks > div:nth-child(2) div:after {
  left: -8px;
  top: 24px;
  box-shadow: 64px 0 0 0 #05114f;
}
.loadingio-spinner-dual-ring-s7tzyhrrfx9 {
  width: 24px;
  height: 24px;
  display: inline-block;
  overflow: hidden;
  background: rgba(241, 242, 243, 0);
}
.ldio-t31fo04ebks {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.24);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-t31fo04ebks div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
