<template>
<div class="spinner-1">
  <div class="loadingio-spinner-pulse-3pnpgc3cva"><div class="ldio-l1cpb39xxx">
  <div></div><div></div><div></div>
  </div></div>
</div>
</template>

<script>
export default {
    name: "Spinner"
};
</script>

<style lang="scss">
@keyframes ldio-l1cpb39xxx-1 {
  0% { top: 21.06px; height: 74.88px }
  50% { top: 35.099999999999994px; height: 46.8px }
  100% { top: 35.099999999999994px; height: 46.8px }
}
@keyframes ldio-l1cpb39xxx-2 {
  0% { top: 24.569999999999993px; height: 67.86px }
  50% { top: 35.099999999999994px; height: 46.8px }
  100% { top: 35.099999999999994px; height: 46.8px }
}
@keyframes ldio-l1cpb39xxx-3 {
  0% { top: 28.08px; height: 60.839999999999996px }
  50% { top: 35.099999999999994px; height: 46.8px }
  100% { top: 35.099999999999994px; height: 46.8px }
}
.ldio-l1cpb39xxx div { position: absolute; width: 17.549999999999997px }.ldio-l1cpb39xxx div:nth-child(1) {
  left: 20.474999999999998px;
  background: #93dbe9;
  animation: ldio-l1cpb39xxx-1 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.2s
}
.ldio-l1cpb39xxx div:nth-child(2) {
  left: 49.724999999999994px;
  background: #689cc5;
  animation: ldio-l1cpb39xxx-2 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: -0.1s
}
.ldio-l1cpb39xxx div:nth-child(3) {
  left: 78.975px;
  background: #5e6fa3;
  animation: ldio-l1cpb39xxx-3 1s cubic-bezier(0,0.5,0.5,1) infinite;
  animation-delay: undefineds
}

.loadingio-spinner-pulse-3pnpgc3cva {
  width: 117px;
  height: 117px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff00;
}
.ldio-l1cpb39xxx {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-l1cpb39xxx div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
